import React, { useState, useEffect } from "react";
import { useNavigate, useParams } from "react-router-dom";
import { resetPassword } from "../../api/AuthAPI";
import FormContainer from "../../components/SmallForms/FormContainer/FormContainer";
import { LOGIN_ROUTE, LANDING_ROUTE } from "../../utils/routerConsts";
import { Spinner } from "react-bootstrap";

// a form to reset password if token isn't expired and its data matches user data
const PasswordResetFormPage = () => {
  const navigate = useNavigate();
  const { token } = useParams(); // the token is generated by the backend and attached to password-reset url
  const [formState, setFormState] = useState({
    newPassword: "",
    confirmPassword: "",
  });
  const [error, setError] = useState("");
  const [isLoading, setIsLoading] = useState(false);

  const clearMessages = () => setError("");

  // useEffect hook to ensure the token exists; if not, redirect to the landing page
  useEffect(() => {
    if (!token) {
      navigate(LANDING_ROUTE);
    }
  }, [navigate, token]); //re-check the presence of the token

  const handleInputChange = (name, value) => {
    setFormState((prev) => ({ ...prev, [name]: value })); // Update the form state with new input values
  };

  const handleSubmit = async (e) => {
    e.preventDefault(); // Prevent default form submission to check data
    setError("");

    if (formState.newPassword !== formState.confirmPassword) {
      setError("Passwords do not match.");
      return;
    }

    setIsLoading(true);
    try {
      await resetPassword(token, formState.newPassword);
      window.alert("Password reset successful!");
      navigate(LOGIN_ROUTE);
    } catch (err) {
      setError(err?.message || "Error occurred. Please try again.");
    } finally {
      setIsLoading(false);
    }
  };

  if (isLoading) {
    return (
      <div id="subsidiary-loading" className="text-center my-5">
        <Spinner animation="border" />
        <p>Loading...</p>
      </div>
    );
  }

  // custom form container for united style
  return (
    <FormContainer
      title="Reset Password"
      fields={[
        {
          name: "newPassword",
          type: "password",
          placeholder: "New Password",
          value: formState.newPassword,
        },
        {
          name: "confirmPassword",
          type: "password",
          placeholder: "Confirm New Password",
          value: formState.confirmPassword,
        },
      ]}
      error={error}
      isLoading={isLoading}
      submitText="Reset Password"
      onSubmit={handleSubmit}
      onInputChange={handleInputChange}
      linkText="Back to Login"
      linkPath={LOGIN_ROUTE}
      clearError={clearMessages}
    />
  );
};

export default PasswordResetFormPage;
